### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-hugeapp#1]
Hi

This looks pretty good and runs well on MAC, not so much on Windows .. but no biggie.
I wanted to ask how can I disable the SSR and enable Client Side Rendering?

You mention to do this in entry.js

But not sure.
Thanks

**Comment by tomitrescak** [comment]
Nevermind. I figured it out, I removed the ssr package and use the original one.
Then, I have removed SSR reference and rewired routes.

I  do have one ... maybe more philosophical question though. Why do you prefer SSR to CSR? Ism't it in the end just more complexity with more data passed between client and server? Is it all just to avoid DDP? Thanks for any explanation.

**Comment by tomitrescak** [comment]
There is one detail though.
When I replaced SSR with CSR it redirects me to "http://localhost:3000/#/?_k=7oa2t6" from the main app. Any idea?

**Comment by eXon** [comment]
The reason I love SSR is purely to improve the user experience. When you do SSR, you already have the first screen ready and you don't need for the app to wait. I hate seeing loading, but I know it is CPU intensive on the server so it is not always ideal.

If you want to run this on Windows, you will need to remove the unix symbol link node_modules and replace it by a Windows symbolic link. I'll add the steps to do in the readme once somebody confirm it is working.

For your redirection, I'm not sure why this is happening. I would need to see your code.

**Comment by tomitrescak** [comment]
Hi, I did the symbol rplacement to no avail. I'll wait ;)
