### ISSUE TITLE
Hot reload issues

### ISSUE THREAD

**Issue by billkell** [thereactivestack/kickstart-hugeapp#11]
When I make a change in my code, the webpack notices and rebuilds, but the change does not show on the page.  Refreshing the page will show the change correctly, but hot reload has not worked regardless of the type of change I've tried.

Any suggestions?

**Comment by eXon** [comment]
Have you tried with a fresh version of this repo? What OS are you on? What have you changed?

**Comment by eXon** [comment]
Hot reload might stop working if you have syntax errors sometimes. Not sure it is entirely in our control.
