### ISSUE TITLE
Installed Node

### ISSUE THREAD

**Issue by steinitz** [thereactivestack/kickstart-hugeapp#13]
Hi,

Your kickstart is great - thank you.

The build process indicated that it installed  node on my Mac even though I had already installed node with homebrew.

I hope this report is useful.

Cheers

**Comment by eXon** [comment]
It doesn't install node on your computer. However, it is installing a local version of NPM. This is needed and will not affect your global NPM version.

**Comment by steinitz** [comment]
Maybe "development mode", i.e. using my Mac as client and server, resulted in a node installation on my Mac.  Thanks for letting me know its a just a 'local version'.

I hope this report is useful.

Cheers
