### ISSUE TITLE
CommonsChunkPlugin throwing Uncaught ReferenceError: webpackJsonp is not defined 

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [thereactivestack/kickstart-hugeapp#15]
I just faced this issue https://github.com/webpack/webpack/issues/368 
Due to this line: https://github.com/thereactivestack/kickstart-hugeapp/blob/448832cb4283f2cd3ad0b3b2bc66a8beca9ad5e6/entry/client/webpack.conf.js#L26

The `Infinity` param didn't work, though :( So I just removed it.

**Comment by eXon** [comment]
This means your common chunk is not loaded. Are you using react-router-ssr package?

**Comment by gabrielpugliese-luizalabs** [comment]
That's it. I had to remove it due to the issue with two reacts I've mentioned here: https://github.com/thereactivestack/meteor-webpack/issues/21

Now I'm using the react-router only on client.

**Comment by eXon** [comment]
I'll close that issue because I don't think anything has to be fixed.
