### ISSUE TITLE
Tests are loading instead of the app

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#16]
I've been running this for a bot and with the latest build, I now get a Jasmine test window displayed when I run in instead of the app. What changed? The docs still say to do what I have been doing, so this is confusing.

**Comment by genyded** [comment]
OK - never mind - the Test window was on top of the app and if I close it the app is there. Is there an way to turn off that test window though? Once that question is answered this can be closed.

**Comment by eXon** [comment]
You can remove velocity:html-reporter from the project. You can insteall velocity:console-reporter for something less intrusive.

**Comment by genyded** [comment]
Got it - thanks!
