### ISSUE TITLE
react-router onEnter hooks and SSR

### ISSUE THREAD

**Issue by skosch** [thereactivestack/kickstart-hugeapp#17]
This isn't a bug per se, but I figured this was the best place to ask this question :)

I have to check whether users are logged in when they're trying to access certain routes. I'd like to use react-router's `onEnter` callback like this:

```javascript
  onEnter(nextState, replaceState, callback) {
    let onLoginCallback = null;
    var checkAndRedirect = function() {
      if (onLoginCallback) {
        onLoginCallback.stop();
      }
      if (Meteor.user().profile.guest) {
        replaceState(null, 'login?redirect=/dashboard');
      }
      callback();
    };

    // sorry, this is a bit convoluted -- Meteor.user() isn't always available
    // right away, so sometimes I have to wait for the login to finish
    if (Meteor.loggingIn()) {
      onLoginCallback = Accounts.onLogin(checkAndRedirect);
    } else if (Meteor.user()) {
      checkAndRedirect();
    }
 }
```
However, when I'm running this in production mode, the redirects aren't working. I can see the URL in the address bar change to `login?redirect=/dashboard`, but the page stays gray – the login page isn't actually loaded until I manually refresh the page. I still don't quite grok how the SSR code deals with route changes, so I'd be super grateful for some pointers regarding `onEnter` and SSR.

**Comment by eXon** [comment]
I'm using Meteor.userId() to check if the user is logged in. I'm not sure it's 100% secure though.

**Comment by skosch** [comment]
I'm using [artwells:meteor-accounts-guest](https://github.com/artwells/meteor-accounts-guest), so technically everybody is logged in, always. That's why I need to check for `Meteor.user().profile.guest`. I guess I'm just confused about where `onEnter` runs. Can routes be changed on the server side at all, or are they purely a client-side thing?

**Comment by eXon** [comment]
SSR is running on the server. This means Meteor.user() should be available right away. Do you have a git I can clone to check why it doesn't work?

**Comment by skosch** [comment]
I don't have a public repo for now, sorry :( (I'd love to have one asap but that's out of my hands)

I'm now able to get an error message on the server side. When I access `Meteor.user()` directly within `onEnter`, I get
```javascript
error while server-rendering Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
W20151111-14:24:55.488(-5)? (STDERR)     at AccountsServer.userId (accounts_server.js:80:13)
W20151111-14:24:55.488(-5)? (STDERR)     at AccountsServer.user (accounts_common.js:53:23)
W20151111-14:24:55.488(-5)? (STDERR)     at Object.Meteor.user (accounts_common.js:230:19)
W20151111-14:24:55.488(-5)? (STDERR)     at Object.e.exports.onEnter ....
```
and when I remove it, and carefully guard everything with `if (Meteor.isClient)`, I still get 
```javascript
W20151111-13:55:45.467(-5)? (STDERR) error while server-rendering TypeError: Cannot read property 'userId' of undefined ...
```
Either way, `replaceState` never gets called on the server, and so the login page never gets delivered even though the client thinks it's showing it.

My understanding is that information about the user generally isn't available on the server side (outside of methods and publications, of course). Unless that's not true in the context of SSR, wouldn't that mean that what I'm trying to do is doomed to fail?

**Comment by eXon** [comment]
OK with that I know enough to replicate it. I could probably stub it to return the correct user. I'll look into that when I have time.

**Comment by skosch** [comment]
That would be amazing, thanks so much. Looks like I'm going back to your react-router-ssr Meteor package after all ;-)

**Comment by eXon** [comment]
After doing some investigation, onEnter is not executed at all on SSR. It seems like this is purely a react-router problem. After looking your code a few times, it looks good to me. I'll try to help you if I have a few more minutes this week.

**Comment by skosch** [comment]
Here's a bit of speculation. `onEnter` is useless on the server, because changing the `location` object doesn't actually do anything. Instead we may actually have to send back a 301 to force the client to re-load the login page from scratch. That is also what's suggested [in the react-router docs](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md).

Whether or not that would lead to `onEnter` being run, I don't know. I also don't see why `Meteor.user()` would be available on the server at that instant – from what I understand, fast-render only provides the userId. Maybe we can use that to get the user object within the `onEnter` though, server-side at least.

I'll experiment some more with this and report back. Any thoughts in the meantime are welcome :)

**Comment by skosch** [comment]
Alright, so the following seems to work okay:

* First, I make sure the user object is available, by excluding `users` from the pseudo-publish,
```javascript
if (this._name === 'users') {
  return originalFindOne.apply(this, args);
}
```
and then grabbing the object from the database (instead of setting it to `undefined`):
```javascript
Meteor.user = () => Meteor.users.findOne({_id: context.userId});
```
... after which it's probably a good idea to monkeypatch `Meteor.users.findOne` to only return data for the current `userId`. I haven't done that yet but the official package probably should.

* Then, instead of directly writing `html = ...`, I use the `match` function:
```javascript
ReactRouter.match({routes, location: req.url}, (err, redirectLocation, renderProps) => {
  if (err) {
    res.status(500).send(err.message);
    responseAlreadySent = true;
  } else if (redirectLocation) {
    res.redirect(302, redirectLocation.pathname + redirectLocation.search);
    responseAlreadySent = true;
  } else if (renderProps) {
    renderProps.history = history;
    html = ReactDOMServer.renderToString(<Router {...renderProps} {...serverOptions.props} />);
  } else {
    res.status(404).send("Not found");
    responseAlreadySent = true;
  }
});
```
Note that `responseAlreadySent` is a flag set to prevent the HTML skeleton from being wired down. Probably not the most elegant way to structure the code, but it works for now.

Also note that the react-router docs use `<RoutingContext />` instead of `<Router />` – I don't know whether the difference is significant; at any rate you can grab it via `const {RoutingContext} = ReactRouter` if you want.

* `onEnter` is definitely run on the server side now. I haven't tested things extensively, but so far I'm having none of the troubles I used to :)

Thoughts so far?

**Comment by eXon** [comment]
I think this will significantly improve SSR. I wasn't aware of ReactRouter.match until today (had to use it on a Node.js project). This makes sense to me.

**Comment by skosch** [comment]
Cool!

Btw, heads up, the `res.status` line that I stole from the react-router docs doesn't work, because it's an Express shortcut. You'll want to use `res.writeHead`, `res.write` and `res.end` instead.

**Comment by eXon** [comment]
Your onEnter should now be treated correctly by SSR! Thanks for the help :)
