### ISSUE TITLE
conflict with ecmascript

### ISSUE THREAD

**Issue by newsiberian** [thereactivestack/kickstart-hugeapp#2]
Hi @eXon, you're doing great work!

I faced with the following error when trying to add package from atmosphere to package folder. Package has 'ecmascript' in dependencies and if I turn it off, package shows me more errors.
```
While determining active plugins:
   error: conflict: two packages included in the app (ecmascript and webpack:webpack) are both trying to handle *.js
``` 

thithout 'ecmascript' in package:
```
...
W20151014-20:12:14.781(6)? (STDERR)   let extra;                                                                  
W20151014-20:12:14.781(6)? (STDERR)       ^^^^^
W20151014-20:12:14.781(6)? (STDERR) SyntaxError: Unexpected identifier
...
```

**Comment by eXon** [comment]
The ecmascript package can be enabled inside packages. However, it cannot be enabled inside your main app. They are both built separately.

Maybe the package is missing the ecmascript dependency. You should send them a bug issue.

**Comment by newsiberian** [comment]
> The ecmascript package can be enabled inside packages.

It is. Package I've put inside /packages folder has ecmascript as dependency.

> However, it cannot be enabled inside your main app.

It is not enabled inside my app,

but I so this error about conflict.

**Comment by eXon** [comment]
This is weird. Maybe smart packages are treated differently. Do you have a repo I can reproduce the bug?

**Comment by newsiberian** [comment]
I put it [here](https://github.com/newsiberian/kickstart-hugeapp/tree/tests)

**Comment by eXon** [comment]
Remove `api.imply("ecmascript");` in your package.json. You're implicitly adding it to your main project and their is no reason to.

**Comment by eXon** [comment]
Make sure no package is using api.imply on ecmascript. This is probably the reason.

**Comment by newsiberian** [comment]
Thank you. That helped)

**Comment by eXon** [comment]
Awesome, I'm sure a lot of people are going to run into the same problem. Also btw I'm not sure what you're trying to accomplish wih package.npm.json? This shouldn't be required with Webpack. I hope it was just a placeholder ;)

**Comment by newsiberian** [comment]
this a fake package. I trying to include reaction-core package.)
