### ISSUE TITLE
No full page reload

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/kickstart-hugeapp#21]
Hi, first congratulations for this, this looks super promising. I'm using the genuine git clone (I just removed the tests) and it looks like while HMR works fine, modifying something in the `client/route.jsx` file does not trigger a full page refresh. The console does show:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HRM] - ./modules/TodoApp/client/routes.jsx
[HMR] Reloading page
```

... but in reality nothing happens.

**Comment by dbismut** [comment]
I might have posted in the wrong repository, [meteor-webpack](https://github.com/thereactivestack/meteor-webpack) would probably have been a better choice. Anyway, I know I had the same issue with a react starter kit, and the solution was to add `reload=true` option to `'webpack-hot-middleware/client?reload=true'` as seen [here](https://www.npmjs.com/package/webpack-hot-middleware#config).

So I guess that option could be added [there](https://github.com/thereactivestack/meteor-webpack/blob/master/plugin/WebpackCompiler.js#L270)?

I know almost nothing about Webpack so I might be wrong.

**Comment by dbismut** [comment]
Ok so I did the test and adding `reload=true` in the `WebpackCompiler.js` file in the `webpack:webpack` package does make the browser refresh automatically when HMR fails:

```
    webpackConfig.entry = [].concat(
      'webpack-hot-middleware/client?reload=true&path=' + webpackConfig.devServer.protocol + '//' + webpackConfig.devServer.host + ':' + webpackConfig.devServer.port + '/__webpack_hmr',
      webpackConfig.entry
    );
```

**Comment by eXon** [comment]
If you update your webpack package, now you can add this to entry/webpack.conf.js (or use any other option):

```
hotMiddleware: {
  reload: true
}
```

**Comment by dbismut** [comment]
Fantastic. Thank you.
