### ISSUE TITLE
render loginButtons server side?

### ISSUE THREAD

**Issue by minfawang** [thereactivestack/kickstart-hugeapp#22]
I noticed that when running in production, the [loginButtons](https://github.com/thereactivestack/kickstart-hugeapp/blob/3d4ddb057c5760c3aa545741483e393fb983e159/modules/TodoApp/client/components/TodoHeader.jsx#L50) are rendered only on the client side. I guess it's technically achievable to also render it on the server side?

**Comment by eXon** [comment]
The reason is because it is a Blaze template (acounts-ui). As far as I know Blaze templates are not available on the server. Most Blaze stuff I use I don't care about server rendering.

Do you have a use-case it would be necessary?

**Comment by minfawang** [comment]
Ok make sense. I'm actually not using `BlazeToReact` in my projects, but I think this might be beneficial for people who are comfortable with Blaze or want to use some Blazed based packages to use webpack and/or SSR. 

Thanks. I will close it.
