### ISSUE TITLE
Code does not seem to see environment

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#23]
I have a MAIL_URL set on the server and no matter what, keep getting Email is undefined (Meteor email package is also installed). Has anyone had success sending email with this repos? If so where and how did you set the MAIL_URL? I've tried it in the root lib/server and in the entry. Does webpack need it somewhere else too?

Thanks!

**Comment by eXon** [comment]
This is because process.env is used by Webpack as well as by Meteor. If you would like to set MAIL_URL, you can set it inside a Meteor.startup.js file. Have you tried that?

**Comment by eXon** [comment]
I haven't found a way yet to configure Webpack to not overwrite process.env. I don't know if it is even possible. Webpack want your value at compile time while your app want it at runtime :/

**Comment by genyded** [comment]
Not sure if this helps or not, but...[here](https://www.npmjs.com/package/webpack-env) is another webpack repo with the same issue mentioned...

**Comment by genyded** [comment]
Closing this since it's just a dev issue with a workaround
