### ISSUE TITLE
Initial data

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#25]
Is there an example anywhere of populating initial data (sometimes called fixtures)? I tried it the way I would in a normal Meteor app, but the collection is not seen (probably a load order or other issue).

**Comment by minfawang** [comment]
I think [this](https://github.com/thereactivestack/kickstart-hugeapp/blob/master/modules/TodoApp/server/__tests__/integration/Todo-fixtures.js) is an example.

**Comment by eXon** [comment]
This is used for unit testing.

You can easily have a modules/ModuleName/server/seed folder. Then a modules/ModuleName/server/index.js that require all of them. Then you require it within entry/server/entry.js.

I'll add an example to the project when I have a few minutes to spare :)

**Comment by genyded** [comment]
Cool - I'll check this out some more. Doesn't Meteor strip out requires though?

**Comment by genyded** [comment]
Non issue - figured it out
