### ISSUE TITLE
Any plans to bring Redux or some other flux flavor into the mix?

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#27]
Any plans to bring Redux or some other flux flavor into the mix? Abstracted state in larger apps seems to be becoming paramount. However, I realize that is a lot of work so if not, it's cool. There are a few other examples out there, but they are REALLY basic leaderboard crap without even any real crud, auth or anything else real world. You stuff is still basic, but at least hits all the core aspects.

**Comment by eXon** [comment]
I found that with Meteor very few things need Redux because we have the subscribers. However, I get it that it is useful for many things. I've updated react-router-ssr to be able to support it. I might make a kickstart-redux project so we don't make this one too complex.

**Comment by eXon** [comment]
I'll close this for now because I don't want to bring redux on this example. However, be sure I'll keep that in mind ;)

**Comment by yched** [comment]
Interested in a few hints as well :-)

I'm able to get this mostly working with something like this :

```js
import { withProps } from 'recompose'
import store from 'client/store'
import Root from 'client/components/Root'

Meteor.startup(() => {
  ReactRouterSSR.Run(routes, {}, {
    // Wrap the router within the <Root> component, bound to our store.
    wrapper: withProps({store}, Root)
  });
}
```
where Root basically wraps in redux's Provider :
let Root = props => {
  return (
    <Provider store={props.store}>
      {props.children}
    </Provider>
  )
}

But I'm stumbing on the following :

- I fail to see where I could add a 
```<script> window.__INITIAL_STATE__ = ${JSON.stringify(store.getState())}</script>``` (or similar) in the server-generated HTML after the rendering was done, so that the client can receive it and initialize its own store with it.
Maybe ReactRouterSSR needs an additional callback in serverOptions to allow manipulating the generated HTML ?

- I haven't figured out yet how to make redux-simple-router's initPath() action fire once the router has matched, so that the store.routing contains the correct routing info

**Comment by yched** [comment]
I solved the 1st issue above by adding
```js
      if (typeof serverOptions.appendCallback !== 'undefined') {
        data = data.replace('</body>', serverOptions.appendCallback() + '</body>');
      }
```
towards the end of ReactRouterSSR's patchResWrite(),

and calling it like that :

```js
import { withProps } from 'recompose'
import store from 'client/store'
import Root from 'client/components/Root'

Meteor.startup(() => {
  ReactRouterSSR.Run(routes, {}, {
    // Wrap the router within the <Root> component, bound to our store.
    wrapper: withProps({store}, Root),
    // After rendering was done, pass the resulting store state to the client
    // so that he can start from there.
    appendCallback: () => `<script>window.__INITIAL_STATE__ = ${JSON.stringify(store.getState())}</script>`
  });
}
```

@eXon : if that sounds reasonable to you, I can submit a PR to https://github.com/thereactivestack/meteor-react-router-ssr ?

**Comment by yched** [comment]
And my second point : 
> I haven't figured out yet how to make redux-simple-router's initPath() action fire once the router has matched, so that the store.routing contains the correct routing info

Fixed that by creating a history with createMemoryHistory() (rather than createMemoryHistory() on the client side) and using the preRender callback to assign the request url  :

```js
import { createMemoryHistory } from 'history'
import { syncReduxAndRouter } from 'redux-simple-router'
import { withProps } from 'recompose'
import store from 'client/store'
import Root from 'client/components/Root'

Meteor.startup(() => {
    const history = createMemoryHistory();
    syncReduxAndRouter(history, store);

    // Do the rendering.
    ReactRouterSSR.Run(routes, {}, {
      // Wrap in the <Root> component, bound to our store.
      wrapper: withProps({store}, Root),
      // Put the matched url in the history, so that it dispatches to the store.
      preRender: (req, res) => history.replace(req.url),
      // After rendering was done, pass the resulting store state to the client
      // so that he can start from there.
      appendCallback: () => `<script>window.__INITIAL_STATE__ = ${JSON.stringify(store.getState())}</script>`
    });
  });
```

I guess maybe ReactRouterSSR could ease that by doing a 
```history = clientOptions.history || history.createMemoryHistory()``` (similar to what it does on the client side) and call the history.replace() itself after matching the route ?

**Comment by eXon** [comment]
It seems like a good starting point to me. I agree we could add a appendCallback and let them set history on server-side too. You can do a PR if you would like.

In the long run, I would rather see a tighter integration where react-router-ssr detect redux and do it for you. It seems to be the winner candidate for flux libraries.

**Comment by yched** [comment]
Hm - actually, my approach above kind of works, but has a fundamental flaw : it creates the redux store *once* on server startup, and then reuses it for all requests. Meaning the second request starts with the state of the store resulting from the first request.

That's not good, each incoming request should create its own fresh store. Not too sure what's the best way to intergrate that in ReactRouterSSR's flow yet.

- We need to create the store in a pre-routing callback on each request (and then put it somewhere where the rest of the processing can use it, not sure where)
- That store then needs to be passed as a prop to the wrapper component (which in a redux app, needs to be some flavor of `<Provider store={store}>{router}</Provider>`)

Still mulling on that :-)

**Comment by yched** [comment]
@eXon : created a PR with what I have at https://github.com/thereactivestack/meteor-react-router-ssr/pull/24

**Comment by eXon** [comment]
Creating the Redux example is on my todo list. Thank you so much for your PR! :+1:
