### ISSUE TITLE
What's up with the weird class names

### ISSUE THREAD

**Issue by Un3qual** [thereactivestack/kickstart-hugeapp#28]
Why and how are the classnames in this format (`TodoApp-import__delete__1Ew6D` and like this in production `_1Ew6D`) rather than just `delete`, and how is this done?

**Comment by minfawang** [comment]
It's because of the use of local css modules. Checkout out the definition of cssLoader in the [webpack config file](https://github.com/thereactivestack/kickstart-hugeapp/blob/master/entry/client/webpack.conf.js#L35)

**Comment by eXon** [comment]
They are what we call local CSS. They are generated by webpack :), In production, they will only be named with the hash (last part). You can configure it in your webpack config.
