### ISSUE TITLE
Where/how is the node_modules symlink getting set?

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#29]
My system has NPM 3.5.1 globally, but running kickstart-hugeapp displays a ton of warning because it cannot update NPM via the symlink.

**Comment by eXon** [comment]
This will be fixed in the next release. This is pretty easy to fix but shouldn't cause you any problem outisde the ugly warnings.

**Comment by genyded** [comment]
Not causing any real 'problems' other than I can't see the regular console output (because there are literally hundreds of warnings) and sometimes I really need to. ETA on the next release?

Thanks!

**Comment by eXon** [comment]
I upgraded to NPM 3.5.2 and it doesn't seem to fix the problem :/ I'm not sure what is causing the problem.

**Comment by genyded** [comment]
Oh well - thanks for trying - I guess I'll live with it for now.

**Comment by genyded** [comment]
maybe [this](https://github.com/npm/npm/issues/10013#issuecomment-164382806)

**Comment by eXon** [comment]
You're right, this is exactly right! I've rollbacked to NPM 2.14.15 and re-activated the warnings.

I'll keep this issue open until NPM fix it and we can go back to NPM 3.

**Comment by eXon** [comment]
In the next meteor-webpack version, you will run `npm install` by yourself (just like in the next Meteor 1.3). This will not be a problem anymore because it will not be a symlink anymore.
