### ISSUE TITLE
Issue out of the box

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#3]
Running this results in:

ERROR in C:/Users/genyd/AppData/Local/.meteor/projects/kickstart-hugeapp-master/
client/entry.js
Module build failed: ReferenceError: Unknown plugin "react-transform"
  at PluginManager.subnormaliseString (C:\Users\genyd\AppData\Local\.meteor\proj
ects\kickstart-hugeapp-master\packages\npm-container\.npm\package\node_modules\b
abel-loader\node_modules\babel-core\lib\transformation\file\plugin-manager.js:14
7:13)
  at PluginManager.add (C:\Users\genyd\AppData\Local\.meteor\projects\kickstart-
hugeapp-master\packages\npm-container\.npm\package\node_modules\babel-loader\nod
e_modules\babel-core\lib\transformation\file\plugin-manager.js:190:40)
  at File.buildTransformers (C:\Users\genyd\AppData\Local\.meteor\projects\kicks
tart-hugeapp-master\packages\npm-container\.npm\package\node_modules\babel-loade
r\node_modules\babel-core\lib\transformation\file\index.js:237:21)
  at new File (C:\Users\genyd\AppData\Local\.meteor\projects\kickstart-hugeapp-m
aster\packages\npm-container\.npm\package\node_modules\babel-loader\node_modules
\babel-core\lib\transformation\file\index.js:139:10)
  at Pipeline.transform (C:\Users\genyd\AppData\Local\.meteor\projects\kickstart
-hugeapp-master\packages\npm-container\.npm\package\node_modules\babel-loader\no
de_modules\babel-core\lib\transformation\pipeline.js:164:16)
  at transpile (C:\Users\genyd\AppData\Local\.meteor\projects\kickstart-hugeapp-
master\packages\npm-container\.npm\package\node_modules\babel-loader\index.js:12
:22)
  at Object.module.exports (C:\Users\genyd\AppData\Local\.meteor\projects\kickst
art-hugeapp-master\packages\npm-container\.npm\package\node_modules\babel-loader
\index.js:69:12)
 @ multi main

I am on Windows and applied the symbolic link change per the readme but the issue persists.

**Comment by eXon** [comment]
You might have to run meteor to get the NPM modules first and rerun it after.

If you click your node_modules folder, is it sending you to a folder with modules?

**Comment by genyded** [comment]
Did that... but I think it's actually the note at the end of the readme to create the symbolic link:

ln -s packages/npm-container/.npm/package/node_modules

...I am on windows and trying to do that fails with  Invalid switch - "npm-container". I think If I can get the correct way to set that link on Windows... it should work.

**Comment by eXon** [comment]
On windows you should use MKLINK not ln.

`MKLINK /D node_modules packages\npm-container\.npm\package\node_modules`

**Comment by eXon** [comment]
Let me know if it works btw

**Comment by genyded** [comment]
I have MKLINK /D node_modules packages\npm-container\.npm\package\node_modules in my node_modules files per your Windows Fix in the readme. So if I then try to run  

MKLINK /D node_modules packages\npm-container\.npm\package\node_modules

...it fails with 'Cannot create a file when that file already exists' because that link already exists.

**Comment by eXon** [comment]
Have you removed the node_modules file?

**Comment by genyded** [comment]
OK I cleaned everything up and started over. I got the symbolic link created:

`symbolic link created for node_modules <<===>> packages\npm-container.npm\package\node_modules`

...but it's still failing on running meteor with the following:

`Module build failed: ReferenceError: Unknown plugin "react-transform"`

**Comment by eXon** [comment]
I've tested it on Windows and it is running without this error. It has to do with the node_modules symbolic link in the root folder. When you double-click your symbolic link does it go into the correct directory?

**Comment by genyded** [comment]
OK I used the tool to create symbolic links on Windows from [here] (http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) and it works. Not sure why doing it from console doesn't though. Anyway got it working for now so closing this.

**Comment by eXon** [comment]
Good to know. I also have the same tool installed. I'll add it to the readme.
