### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined running --production

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#32]
Hi Benoit,

Sorry to be a pest and I usually try to figure things out before I post here, but running this with --production returrns:

`Uncaught ReferenceError: webpackJsonp is not defined`

...and since some of the webpack stuff is hidden 'behind the curtain', I am not sure where to even start looking or what to try.

**Comment by eXon** [comment]
This is caused by the common chunk. It looks like the common.js is not loaded first. I'll take a look.

**Comment by genyded** [comment]
Grrr. my fault - was a missing comma in a nested router file - not your solid stuff.

**Comment by eXon** [comment]
Haha remotely everyone using the common chunk plugin has reported a bug about it, don't worry ;)
