### ISSUE TITLE
Please provide example showing addition of react-bootstrap

### ISSUE THREAD

**Issue by jrothman** [thereactivestack/kickstart-hugeapp#38]
Hi
What is the correct way to add react-bootstrap to the project?

I believe you need to 'require bootstrap.css' somewhere and then import the react-bootstrap components as you need them but would prefer some explicit steps or a code example using your project structure.

**Comment by genyded** [comment]
There is nothing special about this project or structure for react bootstrap. You would just add it like you would any other (assuming you are continuing to use ES6)...

Add react-bootstrap with the version you want to the webpack.packages.json file, then use it in your components:

````javascript
import Button from 'react-bootstrap/lib/Button';
// or
import { Button } from 'react-bootstrap';
````

...then just use them as you would anything else.

**Comment by eXon** [comment]
Thanks for taking the time to care. There is nothing specific to do for react-bootstrap to work. I don't think this is necessary. If you think it would be helpful you can write a blog post or a tutorial :)

**Comment by jrothman** [comment]
Discovered that adding the 'bootstrap-webpack' npm package and requiring it in the client entry.js file was a quick solution.

**Comment by eXon** [comment]
This package seems really cool. Never heard of it before thanks for sharing!

**Comment by infacq** [comment]
basically how do I require any css library using npm? how do I include it in my page

**Comment by eXon** [comment]
@infacq You can import or require a CSS file and it will be automatically bundled with your Meteor app.

```javascript
// Add this at the top of where you need it
import 'module-name/css/test.css';
// or
require('module-name/css/test.css');
```

**Comment by infacq** [comment]
do I have to reference to the `node_module` folder?

**Comment by eXon** [comment]
It works the same way as any import. If the path is relative to the file you're writing use `import './css/file.css';` and if it is within a NPM module, use: `import 'bootstrap/css/file.css`. It will automatically know where to look.

**Comment by infacq** [comment]
thanks @eXon. Actually I thought the import file would take the `sass` file

**Comment by eXon** [comment]
If you have `webpack:sass` within your project, you can do the same thing with `.scss`

**Comment by infacq** [comment]
this guy has same concern as [mine](https://github.com/thereactivestack/meteor-webpack/issues/121). However i hit this error this morning when run `meteor --production`

```
While processing files with webpack:webpack (for target web.browser):
   src/client.js: ./~/bulma/css/bulma.css
   Module parse failed: ~/projectx/node_modules/bulma/css/bulma.css
   Line 1: Unexpected identifier
   You may need an appropriate loader to handle this file type.
   | html, body, body div, span, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre,
   abbr, address, cite, code, del, dfn, em, img, ins, kbd, q, samp, small, strong, sub, sup,
   var, b, i, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody,
   tfoot, thead, tr, th, td, article, aside, figure, footer, header, menu, nav, section, time,
   mark, audio, video, details, summary {
   |   margin: 0;
   |   padding: 0;
   @ ./~/bulma/css/bulma.css 4:14-38
```
