### ISSUE TITLE
Load static html without losing blaze and SSR

### ISSUE THREAD

**Issue by D1no** [thereactivestack/kickstart-hugeapp#39]
I want to incorporate a mobile framework that relies on multiple **top level divs to be right under the body tag**. So I would like to use multiple components rendered to the static HTML structure first served.

Just adding the static-html package to meteor would kill blaze and the html is not visible to webpack for SSR. How can I mitigate that?

In the end I want to render multiple components to different areas of the first-served html under a route. I googled a lot and checked ReactRouterSSR and the render methods:
But what is the best way to give webpack an html starting point to render react components into while using ReactRouterSSR...? I am a little bit lost

**Comment by eXon** [comment]
This is a hard one because Blaze (or static-html) will not set the HTML at the right time. What end-result are you trying to accomplish with your HTML? Do you have an example?

**Comment by D1no** [comment]
Yeah, I just realized that. I am just going through the source code of ReactRouterSSR and found that you're engeneering the "rootElement". Adding a class property to it will probably already help in this case. But I'll try to explain.

As an exercise I am merging the To-Do Kistart-Simple App with [Framework7](http://www.idangero.us/framework7/) which is a pretty solid mobile frontend we are using for a mobile web-site/app. The sucky part: The author is not really keen on MVC frameworks and relies alot on ajax and generic dom-manipulation for different views etc.

However, there is a [inline page/dom option](http://www.idangero.us/framework7/docs/pages-inline.html) which could be managed by react. But the css-selector inheritance is not easily changeable so there are many elements where we can not simple stick wrapper divs in between (like the `<div id="react-app ></div>` without passing it also the required classes etc.

So we need to render multiple elements directly under the body tag. Take a look at the generic structure:
```html
<body>
  <div class="statusbar-overlay"></div>
  <div class="panel-overlay"></div>
  <div class="panel panel-left panel-reveal">
    <div class="content-block">
      <p>Left panel content goes here</p>
    </div>
  </div>
  <div class="panel panel-right panel-cover">
    <div class="content-block">
      <p>Right panel content goes here</p>
    </div>
  </div>
  <div class="views">
		<div class="view view-main">(...)</div>
  </div>
</body>
```

I want to achieve something like this. 5 Areas of React-Components
```html
<body>
  <div id="react-app-statusbar-overlay" class="statusbar-overlay"></div>
  <div id="react-app-panel-overlay" class="panel-overlay"></div>
  <div id="react-app-panel-left" class="panel panel-left panel-reveal">
    <div class="content-block">
      <p>Left panel content goes here</p>
    </div>
  </div>
  <div id="react-app-panel-right"  class="panel panel-right panel-cover">
    <div class="content-block">
      <p>Right panel content goes here</p>
    </div>
  </div>
  <div id="react-app" class="views">
		<div class="view view-main">(...)</div>
  </div>
</body>
```

What I do now is porbably to fork ReactRouterSSR and hack it to either mount to the body tag so the 5 components above are router child components or add a rootElementClass Argument (to style the root element analog to the blueprint) and figure out a way to render multiple on one SSR requrest.

I guess most elegantly, the ReactRouterSSR should probably fetch meteors HTML (Blaze.renderToHTML) and use cherio to find the node that matches the specified rootElements to render them into the given HTML.
