### ISSUE TITLE
Local packages

### ISSUE THREAD

**Issue by jhartma** [thereactivestack/kickstart-hugeapp#4]
I haven't really wrapped my head around webpack, but from what I see how the example app is structured, I wonder how one would include local packages. How would you do this?

**Comment by eXon** [comment]
Don't use a local package unless it is absolutly necessary. You can add folders to your modules folder instead. They are not automaticlly added. It is using the es6 modules (import).

If you really need a local package, add it to the packages folder and export a global variable. It will be available just like in any Meteor app.

**Comment by jhartma** [comment]
Okay cool, thanks
