### ISSUE TITLE
affected by meteor 1.3 ?

### ISSUE THREAD

**Issue by dcsan** [thereactivestack/kickstart-hugeapp#41]
I'm wondering if the upcoming possibilities to work with modules in meteor 1.3 will require/enable a rewrite of this project?

**Comment by eXon** [comment]
Meteor-webpack 1.0 will support meteor 1.3. It will be released in the upcoming weeks :)

**Comment by infacq** [comment]
is there any to annouce?

**Comment by eXon** [comment]
The 1.0 has been released. You should be able to use it with meteor 1.3
