### ISSUE TITLE
Is webpack.packages.json a standard packages.json file?

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#43]
Should/will webpack.packages.json behave like any standard packages.json file? I noticed the default does not have any 'sections' like dev and dependencies. Just want to make sure it should work normally before I modify it.

TIA!

**Comment by eXon** [comment]
No it is not. It is actually building a package.json file in .meteor/local/npm-webpack.

In meteor-webpack 1.0, you will no longer need that file. It will be a plain package.json file. It will be released in the upcoming weeks :)
