### ISSUE TITLE
Why do reloads take so long?

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#45]
If I change a js/jsx file and save it, the build churns with `processing files with webpack:webpack' for several seconds (maybe even minutes). I am just making a minor change to a js file, so why does npm even need to be involved?

![image](https://cloud.githubusercontent.com/assets/3081676/12190796/8086a1be-b592-11e5-8c80-225479279f45.png)

**Comment by eXon** [comment]
Is it a file within a client folder? On what OS are you?

**Comment by genyded** [comment]
The OS is win10 and the files are NOT in a client folder (why do they HAVE to be?).

**Comment by genyded** [comment]
OK - I moved the files to a client folder and it resolved the issue. However, it was/is not obvious to me that this was needed so you may want to put it in the readme in bold red or something. Also I do not see why anything in the `modules` folder ignores `node_modules` without having to be in a client folder, but maybe I am missing something. This can be closed unless you want to use it as a reminder to make this clearer in the readme or change it.

**Comment by eXon** [comment]
The reason is I can block Meteor from reloading on the client but not on the server. If you change a file that is available to the server, your whole app has to be reloaded and the hot reload will not work.

I agree this should be documented better. I'll add something.

**Comment by genyded** [comment]
Cool - do you have a rough timeline on being able to keep dev-dependencies out of the build?

**Comment by myknbani** [comment]
When this kickstarter was upgraded to Babel 6 it seems that reloads have become slower.

**Comment by grsabreu** [comment]
That's true. If I change a any file the  `processing files with webpack:webpack` almost never ends.
If I change some client file I get the client changed properly but  `processing files with webpack:webpack` continues loading blocking any server operation.

**Comment by grsabreu** [comment]
Maybe is a Meteor issue indeed

**Comment by eXon** [comment]
meteor-webpack 1.0 should be a lot faster. Le me know if it's too fast after the release! (march 1st).
