### ISSUE TITLE
Strange new errors

### ISSUE THREAD

**Issue by genyded** [thereactivestack/kickstart-hugeapp#46]
All of a sudden and without (knowingly) changing anything, I am getting a bunch of errors along the following:

ERROR in ./modules/AdminApp/client/AdminApp.jsx
Module build failed: SyntaxError: C:/Users/genyd/AppData/Local/.meteor/projects
kickstart-hugeapp-master/modules/AdminApp/client/AdminApp.jsx: A semicolon is r
quired after a class property (10:3)
   8 |   static propTypes = {
   9 |     children: PropTypes.any.isRequired
> 10 |   }
     |    ^
  11 |
  12 |   render() {
  13 |     return (

Anyone else seeing these or have any idea why these are coming up all of a sudden? I am using the latest kickstart hugeapp and it's been working fine up until now and as I said I did not change anything that I am aware of...

**Comment by eXon** [comment]
This might be because of your stage level on babel. Are you using stage-0?

**Comment by genyded** [comment]
All I did was download the latest and try to run it, so I assume so but will double check.

**Comment by genyded** [comment]
The only visible signs of anything I see are...

`var babelSettings = { presets: ['react', 'es2015', 'stage-0'] };`

in the webpack config for both client and server in the entry folders. Any thoughts on what or where else to check?

**Comment by eXon** [comment]
That's weird. Maybe it is because of a new version. I'll take a look when I get home.

**Comment by genyded** [comment]
Completely dead in the water here... getting an older version has the same issue... am I the only one?

**Comment by dbismut** [comment]
You might have certainly tried it, but did you try adding a semi colon after the closing brace as suggested by the error prompt? I'm pretty sure it won't work since I'm not using semi colons either, but you never know...

```javascript
static propTypes = {
  children: PropTypes.any.isRequired
};
```

**Comment by dbismut** [comment]
After investigating, this seems to be related to Babel 6.4, many people seem to have the same problem: https://github.com/davezuko/react-redux-starter-kit/issues/405. Reverting to previous version of Babel 6.3.xx or adding the semi colons after class properties (`static propTypes = {...};`) fixes this.

But yes, this does break the app at the moment.

**Comment by genyded** [comment]
Yep.. sad part is that the semi-colon stuff is 'supposed' to be experimental ES7 stuff - or so I thought. That means stage-0 should not manifest it. Also any real app based on the framework will have hundreds or thousands of these in several files, so 'fixing it' by adding the semi-colons is not a trivial task.

**Comment by dbismut** [comment]
Well `stage-0` is experimental, isn't it? Anyway, should you want to fix this you just have to set Babel version to 6.3.26 or so in `webpack.packages.json` and you should be good to go. In any case, this is not an issue specific to the hugeapp project even though @eXon might want to fix this to make sure it works out of the box.

**Comment by genyded** [comment]
hugeapp has Babel set to [6.3.x] (https://github.com/thereactivestack/kickstarthugeapp/blob/master/webpack.packages.json) and this still seems to happen...

**Comment by dbismut** [comment]
Look at your `kickstart-hugeapp/node_modules/babel-core/package.json` file and it should be set to 6.4.0. I think you need to set the version as in `"babel-core": "6.3.26"` without the `^`.

**Comment by genyded** [comment]
Closing this because this is a babel issue. Another issue can be opened to add the semi-colons if the reactivestack if desired.
