### ISSUE TITLE
How to update NPM dependencies?

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/kickstart-hugeapp#47]
Hey - noob question I'm sure. How are you supposed to update the `webpack.packages.json` dependencies? I tried `npm update` but this doesn't seem to produce the desired effect (it crashes the app and I have to delete the whole `node_modules` folder and run `meteor` again.)

**Comment by eXon** [comment]
Their is no such command for now. The next version will be using a regular package.json so you'll be able to do it but for now, you can't.

**Comment by eXon** [comment]
For now you have to update the numbers manually
