### ISSUE TITLE
Where to place common code?

### ISSUE THREAD

**Issue by skosch** [thereactivestack/kickstart-hugeapp#5]
The Readme states that code common to all modules will be bundled into one `common.web.js` file. I have a lot of such common code, including collections/subscriptions, components, CSS, images, methods, etc., which should be shipped with all modules except for the public-facing homepage. Where do I place this code?

**Comment by eXon** [comment]
You have nothing to configure. Webpack will figure out where to put your code. As long as your admin is splitted from the rest, it will not be loaded until you access it.

**Comment by skosch** [comment]
Hm, maybe I didn't make myself clear. I have about seven or eight modules, none of which should be loaded until they're accessed. Three of them share a bunch of methods (but also have their own), they share certain UI components, and collections/subscriptions as well.

In other words, I'm having some trouble understanding why you structured the example app the way you did – I suppose it's not huge enough for me to really see the underlying principles. Is there method to the madness, or can I structure things any way I like and webpack will figure things out purely from the `require`/`import` lines?

**Comment by eXon** [comment]
The code splitting logic for the admin is inside modules/AdminApp/client/index.js.
Wepack will automaticlly generate web.js, 01.web.js, 02.web.js, etc.

The common.web.js is more about libs that you use everywhere. It is a Webpack plugin that will figure it out for you. But it will not contain everything that might be common.

Let's say you have an app chunked like this:

- app (web.js / common.web.js)
- TodoApp (01.web.js)
- Admin App (02.web.js)
   - Dashboard (03.web.js)
   - Users (04.web.js)
   - Projects (05.web.js)

The code that is shared between all the application will be inside common.web.js.
The code that is shared by your admin will be inside 02.web.js.

But you don't have to figure this out. Webpack will do it for you.

If you want to change every folder in this project, you can. This is just a kickstart project to help get started quickly. The only thing you need to respect is to put client code inside a client folder and server code inside a server folder. But this is handled by Meteor.

**Comment by eXon** [comment]
If you want to share common code for the admin, you can do it by using the correct settings on the CommonsChunkPlugin. [You can read more about it here.](https://github.com/webpack/docs/wiki/optimization)

You can specify that you want the common code for the admin chunk. So you can do it like this:
```javascript
new CommonsChunkPlugin({
  name: 'admin-common',
  filename: 'admin-commons.js',
  chunks: ['admin-dashboard', 'admin-users', 'admin-projects']
});
```

**Comment by eXon** [comment]
You'll have to make sure admin-common.js is loaded before loading those chunks. I don't think Webpack automate that part.

**Comment by skosch** [comment]
Okay, I suppose I'll actually have to read up on webpack configuration, no shortcuts there ... thanks for your help! :)

**Comment by skosch** [comment]
Sorry, I need to bother you a bit more ... I think I've worked out my multiple entry points in `entry/client`, and I've declared that I want two commons chunks, but I'm not sure how to set things up on the server side.

In your example app, you simply `require('../client/routes')` from the server entry script. In my case, I have multiple client entry points/routes, only *some* of which I'd like to use SSR for. If I simply `require` only those SSR routes after the `ReactRouterSSR.LoadWebpackStats(...)` line, will that work?

**Comment by eXon** [comment]
It's not that easy. When you require('../client/routes') it is using ReactRouterSSR command. On the client, it is rendering it to the DOM and on the server it is rendering it to a string, collect the data with it and send it over the wire. The other routes files are purely objects and do nothing.

You would probably need something to disable SSR on parts of your Website (I'm guessing it's the admin?). 

You can probably add a component that will block the SSR like this:

```javascript
import { Component } from 'react';

export default class BlockSSR extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  componentDidMount() {
    this.setState({ mounted: true });
  }

  render() {
    if (!this.state.mounted) {
      return null;
    }

    return this.props.children;
  }
}
```

This takes advantage of the fact that server-rendering never goes as far as `componentWillMount()`, never inside `componentDidMount()`. The SSR will stop there but the client will go down the hierarchy.

**Comment by skosch** [comment]
Phew. That's an interesting approach, and certainly not one I would've come up with on my own. Thank you! I'll try it out and report back here.

It's not exactly admin, but you're right, it's the section for logged-in users that probably wouldn't benefit enough from SSR to make it worth the server load. The static, cacheable, public-facing sites on the other hand may actually benefit from pre-compilation.

**Comment by skosch** [comment]
So, I'm running into trouble with a `ReferenceError: window is not defined`. Some of my components are stuck using jQuery unfortunately due to huge dependencies, and I suspect that one of them is the culprit.

Although I've tried to block SSR for these components using your suggestion above (and also made the relevant `import`/`require` lines conditional on `window` being defined) I'm still stuck with the error. Do you have any clue how I could possible trace where the problematic `window` may be? Could this mean that the above suggestion isn't blocking SSR like it should, or am I simply missing something else?

**Comment by eXon** [comment]
jquery can be run on the server without any problem. However, you have to make sure that any call within componentWillMount() / first render() do not touch the DOM. 

For example, if you would like to do `$(window).on('resize', this.handleResize.bind(this));`, you have to do it inside componentDidMount().

Those bugs can be hard to track so I would disable a part of my code and reenable it piece by piece. It seems like the call stack isn't working fine so I'll have to check why.

BTW make sure you only call require.ensure when you are on the client. Code splitting only makes sense on the client. The server needs all the code loaded anyway.

If you have a git repo I could look at I might be able to help more if this isn't enough.

**Comment by skosch** [comment]
Yeah, the part-by-part enabling is what I'm doing at the moment. I didn't realize `componentWillMount()` was off limits, though. That's good to know, and may in fact explain my troubles. Thanks a million for all of your work and help, Benoît, it's really incredibly useful!

I wish I could post the code, but I'm not [yet – I hope!] allowed to publish it here :(
