### ISSUE TITLE
!!Build error!! Newest version of Hugeapp doesnt work!!

### ISSUE THREAD

**Issue by MaxArrowhead** [thereactivestack/kickstart-hugeapp#54]
Using:
Windows 10
npm version: 3.6.0
node version: 4.2.6

error during build (typing "meteor" in cmd):
=> Errors prevented startup:

   While processing files with webpack:webpack (for target web.browser):
   plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM
   at runNpmInstall (plugin/WebpackCompiler.js:169:11)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)

   While processing files with webpack:webpack (for target os.windows.x86_32):
   plugin/WebpackCompiler.js:169:11: An error occured while installing your NPM
   at runNpmInstall (plugin/WebpackCompiler.js:169:11)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:71:7)

=> Your application has errors. Waiting for file change.

I already did "meteor update" and updated some packages to the newest version.
my node and npm versions are the latest.

Please help, I have no idea where to start.

**Comment by eXon** [comment]
Hey thanks for reporting.

Go in your .meteor/local/webpack-npm folder and run npm install. Do you see an error?

**Comment by MaxArrowhead** [comment]
I think this bug comes because windows has a limitation of path-length. If i clone the hugeapp repository to my desktop everything is fine.

Issue can be closed.

**Comment by john-osullivan** [comment]
Yeah, I'm running into that path-length limitation as well and it's a little annoying.  Trying to delete the `webpack-npm` folder to prevent cached modules from being used, but the directories are too long to be deleted >_<  Windows problems.
