### ISSUE TITLE
Adding sanitize-html to webpack.packages.json breaks webpack

### ISSUE THREAD

**Issue by grsabreu** [thereactivestack/kickstart-hugeapp#58]
So, I'm not a webpack expert, maybe is something silly that I don't know. But simply adding sanitize-html package breaks the entire webpack load.

```
Module parse failed: /home/gabriel/projects/js/meteor/kickstart-hugeapp/.meteor/local/webpack-npm/node_modules/sanitize-html/node_modules/htmlparser2/node_modules/entities/maps/xml.json Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.
| {"amp":"&","apos":"'","gt":">","lt":"<","quot":"\""}
| 
 @ ./.meteor/local/webpack-npm/~/sanitize-html/~/htmlparser2/lib/Tokenizer.js 6:16-49
./.meteor/local/webpack-npm/~/sanitize-html/~/htmlparser2/~/entities/maps/decode.json
```
That just after adding sanitize-html

Here I forked the current kickstart-hugeapp and just add it and got the error.
https://github.com/grsabreu/kickstart-hugeapp

**Comment by john-osullivan** [comment]
You need to add in the JSON loader for webpack to `webpack.packages.json`:
```
"json-loader": "^0.5.4",
```
I'm surprised that it isn't built-in to `kickstart-hugeapp` already, but I suppose none of the current packages are using it.

**Comment by grsabreu** [comment]
oh, thanks!
I ended up using another package, but really appreciate the tip
