### ISSUE TITLE
How to get static server asset?

### ISSUE THREAD

**Issue by SenerDemiral** [thereactivestack/kickstart-hugeapp#6]

**Comment by skosch** [comment]
I've struggled with this for a bit as well. The answer is: webpack should handle it. You can `require` anything, anywhere, pretty much.

Examples:
* `<img src={require('./img/photo.jpg')} />` will work;
* `require('./styles/style.css')` within `componentWillMount()` will work,
* `background-image: url('./img/photo.jpg')` within a CSS file should work too, etc.

When it doesn't, and you're sure you got the path right, you may have to instruct webpack how to deal with particular filetypes (near the bottom of `client/entry.js`). Tip: there are webpack plugins for any filetype under the sun, e.g. less/sass files, fonts, even images that get inlined as base64. Google "webpack loaders".

**Comment by SenerDemiral** [comment]
private folder should be at application root.

**Comment by SenerDemiral** [comment]
I try to use on server
    var data = JSON.parse(Assets.getText("bb.json"));

**Comment by skosch** [comment]
Ah, you mean Meteor's `Assets` commands? That's a good question. Why not use webpack though? That's exactly what it's there for.

**Comment by SenerDemiral** [comment]
Because, I do not know how to

**Comment by skosch** [comment]
Easy. Put your file wherever you like, preferably close to where you actually need it. Then pull it in by simply calling `require('./bb.json')`, or wherever you put it.

Now you just have to tell webpack to bundle up JSON files. Open `entry/client/webpack.conf.js` (and `entry/server/webpack.conf.js` if necessary) and add an appropriate line in the `loaders` array. [Here is a list](https://webpack.github.io/docs/list-of-loaders.html) of available loaders, you'll want the [JSON](https://github.com/webpack/json-loader) one (which you may have to add to your `package.json` first).

**Comment by SenerDemiral** [comment]
Thanks, I will try.

**Comment by SenerDemiral** [comment]
I added  "json-loader": "0.5.3" to packages.json,
and used in server as 
var data = require("json!./ee.json");
It works, thanks again.

**Comment by skosch** [comment]
Awesome! You should close the issue.

**Comment by eXon** [comment]
Using json-loader to read json file is definitively the way to go. We really need more examples / tutorials of Webpack with Meteor. Working on that soon :)
