### ISSUE TITLE
startup.js file

### ISSUE THREAD

**Issue by SenerDemiral** [thereactivestack/kickstart-hugeapp#7]
In app/entry/server/entry.js file
```
import 'Siparis/server/startup';
```
In app/modules/Siparis/server/startup.js file
```
import BB from 'Siparis/collections/BB';
```
throws error
```
W20151017-21:03:15.203(3)? (STDERR) /root/Desktop/rr4-wp/.meteor/local/build/programs/server/app/modules/Siparis/server/startup.js:1
W20151017-21:03:15.203(3)? (STDERR) (function(Npm, Assets){(function(){import BB from 'Siparis/collections/BB';
W20151017-21:03:15.203(3)? (STDERR)                                    ^^^^^^
W20151017-21:03:15.205(3)? (STDERR) SyntaxError: Unexpected reserved word
```
is startup.js reserved word/file?
when changed to startup222.js, it works!

**Comment by eXon** [comment]
Oh god, I was scared of that, totally my fault.

Every startup.js files are handled by Meteor instead of Webpack. I need a better way of naming that. I'll change it and I'm pretty sure it will work again.

**Comment by eXon** [comment]
I've changed it to meteor.startup.js. A lot less chance to have name conflicts. Thanks for reporting!

**Comment by SenerDemiral** [comment]
What a awesome energy you have!, thanks.
