### ISSUE TITLE
Deployed app doesn't work

### ISSUE THREAD

**Issue by coniel** [thereactivestack/kickstart-hugeapp#8]
I tried deploying my app to a meteor.com test subdomain (simply using meteor deploy ...) and all I see is an empty page (no errors in the console or server logs). So I tried downloading this repo and just deploying that (see http://huge-app-test.meteor.com) and that doesn't work either (same problem). Not really sure what to do since there aren't any errors.

If I do ```meteor run --production``` locally it works. Am I missing a step or something?

**Comment by eXon** [comment]
It is because it is not detecting that meteor deploy should be running in production mode, not debug. I'll add it to the list of commands to detect.

**Comment by eXon** [comment]
Should be fixed in the last release!
