### ISSUE TITLE
React 0.14?

### ISSUE THREAD

**Issue by st3phan** [thereactivestack/kickstart-hugeapp#9]
I'm trying to install React 0.14 instead of 0.13 that comes with the meteor react package. 

* Removed react-runtime package from meteor packages
* Added `"react": "^0.14.0"` to webpack.packages.json
* Removed react from the  webpack externals config option

After that running the app still shows me React 0.13.3 is installed.

Any pointers on how to accomplish this? Is it even possible with Meteor?

**Comment by mattkrick** [comment]
1. You'll have to remove every meteor package that relies on react (including the mixin, blaze components, and ssr). Also cut those packages from the externals in the entry point.  
2. you'll need `react-dom` for ^0.14.0 (and well as the `react-router` from npm)
3. you'll need to serve up the modules without using the SSR package (this is the part where I'm stuck)

I definitely agree with you. I think the way forward is to cut the dependency between react & meteor as soon as possible so we're not dependent on MDG's react releases. It's not easy though.

**Comment by tomitrescak** [comment]
@mattkrick There is an alternative meteor webpack project @ https://github.com/jedwards1211/meteor-webpack-react that is doing just that. It is more independent of meteor, faster and more flexible. The down part is that it has quite large boilerplate and is not as intuitive as Benoit's solution.

**Comment by eXon** [comment]
I'll take a look at it. I believe Meteor is on the verge of releasing 0.14 but it's been forever.

**Comment by eXon** [comment]
Package has been updated to 0.14
